dateModified: 1675165550
email:
  fromEmail: pawarsuraj575@gmail.com
  fromName: demo
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    61212099-be40-4578-9877-06d0fdced990: demo
    a363e452-ddba-4823-bd9c-c65477d9c0e5: Common
    cf3f071c-4a46-44ee-9ead-a68bb53cdb0a: demo
system:
  edition: solo
  live: true
  name: demo
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
