defaultPlacement: end
enableVersioning: true
handle: profile
name: Profile
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9335a8b9-5970-4b13-ba94-62ea6ad0bee3: # cmscraft
    enabledByDefault: true
    hasUrls: true
    template: profile/_entry
    uriFormat: 'profile/{slug}'
type: channel
